- Media:
    - qBittorrent:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/qbittorrent.png
        href: urltocontainer:port
        container: qbittorrent
        widget:
            type: qbittorrent
            url: urltocontainer:port
            username: user
            password: password    
    - MeTube:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/metube.png
        href: urltocontainer:port
        container: metube

- Content:
    - Minecraft:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/minecraft.png
        widget:
            type: minecraft
            url: udp://ipofserver:port   
    - Jellyfin:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/jellyfin.png
        href: urltocontainer:port
        container: jellyfin
        widget:
            type: jellyfin
            url: urltocontainer:port
            key: yourjellyfinapikey

- Utilities:
    - Portainer:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/portainer-alt.png
        href: urltocontainer:port
        container: portainer
        widget:
            type: portainer
            url: urltocontainer:port
            env: 2
            key: portainerapikey
    - SSH:
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/shell.png
        href: urltocontainer:port
    - UptimeKuma:
        href: urltocontainer:port
        icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/uptime-kuma.png?raw=true
    - PiHole:
        href: urltocontainer:port
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/raspberrypi.png
        container: pihole
        widget:
            type: pihole
            url: urltocontainer:port
            key: yourpiholeapikey
    - Soulsender.me:
        icon: https://raw.githubusercontent.com/Soulsender/Soulsender.github.io/0e0ebb76738fe9bcbd6b510d050f6fc73fce4f5f/favicon.svg
        href: https://soulsender.github.io
        ping: https://soulsender.github.io
    - Gluetun:
        container: gluetun
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/openvpn.png
    
